<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DEV_DEL_DEEPAK" ignored="0" name="RetryMultipleFailedTestCases" tests="9" failures="2" timestamp="30 Apr 2020 10:20:37 GMT" time="0.13" errors="0">
  <testcase name="test" time="0.026" classname="com.retrylogic.MyTests">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.006" classname="com.retrylogic.MyTests">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.005" classname="com.retrylogic.MyTests">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.004" classname="com.retrylogic.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.retrylogic.MyTests.test(MyTests.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test1" time="0.001" classname="com.retrylogic.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="com.retrylogic.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="com.retrylogic.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="com.retrylogic.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.retrylogic.MyTests.test1(MyTests.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="com.retrylogic.MyTests"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
